In [1]:
import numpy as np

In [2]:
a=np.array([[[1,2,3],[4,5,6]],
            [[7,8,9], [10,11,12]]])
b=np.array([1,2,3])
a-b

array([[[0, 0, 0],
        [3, 3, 3]],

       [[6, 6, 6],
        [9, 9, 9]]])

In [4]:
a=[[ 0,  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  0.  1.  0.  0.  0.  0.]                      
 [ 0.  0.  1.  0.  0.  0.  0.]                      
 [ 0.  0.  0.  0.  1.  0.  0.]                      
 [ 1.  0.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  0.  0.  0.  1.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 1.  0.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  0.  0.  0.  1.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]                      
 [ 0.  1.  0.  0.  0.  0.  0.]] 

SyntaxError: invalid syntax (<ipython-input-4-be4ab4f8356c>, line 1)

In [16]:
import tensorflow as tf
a = [[0.8,0.3,0.4],[3,4,6]]
b = [1,0,0]
# class_weights = tf.constant([0.3, 0.1, 0.2, 0.3, 0.1])
# l = tf.losses.sparse_softmax_cross_entropy(labels=b, logits=a, weights=[0.8,0.1,0.1])
a_r = tf.reduce_max(a, axis=1, keep_dims=True)
a_m = tf.subtract(a, a_r)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    m=sess.run(a_r)
    print(sess.run(a_m))

[[ 0.  -0.5 -0.4]
 [-3.  -2.   0. ]]


In [23]:
weight_sample = np.array([1113,6705,514,327,1099,115,142])/10015
print(weight_sample)
weight_sample_ = 0.05132302/weight_sample
print(weight_sample_)
weight_sample__ = 0.66949576/weight_sample
print(weight_sample__)
print(4.4695656/0.07665922)

[0.1111333  0.66949576 0.05132302 0.03265102 0.1097354  0.01148278
 0.01417873]
[0.46181496 0.07665922 1.00000009 1.57186558 0.46769795 4.46956561
 3.61971863]
[ 6.02425879  1.00000001 13.04474715 20.50458727  6.10100094 58.30434814
 47.21831012]
58.30434486549694


In [32]:
2*6*22*22
2*2*22*22

1936

In [36]:
a = np.arange(5808).reshape(2,6,22,22)
b = np.arange(1936).reshape(2,2,22,22)
c = b
np.tensordot(a, b, axes=([1],[1])

SyntaxError: unexpected EOF while parsing (<ipython-input-36-6cc8038ebd9b>, line 4)